version: '3.8'

services:
  db:
    image: postgres:14
    container_name: nest_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRES_IN: 60m
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nestnetwork

volumes:
  pgdata:

networks:
  nestnetwork:
